services:
  zrok:
    image: ghcr.io/ilinyhgleb/zrok-share:dev

    environment:
      ZROK2_TARGET: http://n8n:5678
      ZROK2_MODE: public

    volumes:
      - /mnt/apps/configs/n8n-zrok/zrok-config:/home/ziggy/.zrok2:ro
      - /mnt/apps/configs/n8n-zrok/zrok-shared:/home/ziggy/shared

    networks:
      - n8n-zrok

    restart: unless-stopped

    depends_on:
      - n8n

  n8n:
    image: ghcr.io/ilinyhgleb/n8n-zrok:latest

    user: "1000:1000"

    environment:
      N8N_HOST: n8n
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      N8N_SECURE_COOKIE: "false"

      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}

      EXECUTIONS_MODE: queue
      QUEUE_BULL_REDIS_HOST: redis
      QUEUE_BULL_REDIS_PORT: 6379

    volumes:
      - /mnt/apps/configs/n8n-zrok/n8n-data:/home/node/.n8n
      - /mnt/apps/configs/n8n-zrok/zrok-shared:/shared:ro

    ports:
      - "5678:5678"

    networks:
      - n8n-zrok

    restart: unless-stopped

    depends_on:
      - postgres
      - redis


  postgres:
    image: postgres:17

    environment:
      POSTGRES_DB: n8n
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - /mnt/apps/configs/n8n-zrok/postgres-data:/var/lib/postgresql/data

    networks:
      - n8n-zrok

    restart: unless-stopped


  redis:
    image: redis:7

    networks:
      - n8n-zrok

    restart: unless-stopped


networks:
  n8n-zrok:

