services:
  zrok:
    image: ghcr.io/ilinyhgleb/zrok-share:dev

    environment:
      ZROK2_TARGET: http://n8n:5678
      ZROK2_MODE: public

    volumes:
      - ./zrok2:/home/ziggy/.zrok2:ro
      - ./zrok-shared:/home/ziggy/shared

    networks:
      - zrok-n8n

    restart: unless-stopped

  n8n:
    build:
      context: ./n8n
      dockerfile: Dockerfile

    environment:
      N8N_HOST: n8n
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      N8N_SECURE_COOKIE: "false"

    volumes:
      - ./n8n-data:/home/node/.n8n
      - ./zrok-shared:/shared:ro

    ports:
      - "5678:5678"

    networks:
      - zrok-n8n

    restart: unless-stopped

    depends_on:
      - zrok

networks:
  zrok-n8n:
